version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - mysql-volume:/var/lib/mysql 
  db-test:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3000:3306
    env_file:
      - ./.env.test
volumes:
  mysql-volume:
